export const FETCH_PLAT_REQUEST = 'FETCH_PLAT_REQUEST';
export const SAVE_PLAT_REQUEST = 'SAVE_PLAT_REQUEST'
export const UPDATE_PLAT_REQUEST = 'UPDATE_PLAT_REQUEST'
export const PLAT_SUCCESS = 'PLAT_SUCCESS';
export const PLAT_FAILURE = 'PLAT_FAILURE';
